---
title: "Assignment9"
output: html_notebook
---


```{r}
library(tidyverse)
library(Stat2Data)
```

## 2

```{r}
hawks_total <- Hawks %>% filter(Species=="SS" | Species=="CH") %>% mutate(labels=case_when(
  Species == "SS" ~ 0,
  Species == "CH" ~ 1
)) %>% select(c("Weight", "Wing", "Tail", "Hallux", "labels")) %>% rename(Species=labels) %>% drop_na()

hawks_total
```

```{r}
num_total <- hawks_total %>% nrow()
num_trains <- floor(num_total*0.6)
num_test <- num_total - num_trains

set.seed(123)

test_inds <- sample(seq(num_total), num_test)
train_inds <- setdiff(seq(num_total), test_inds)

hawks_train <- hawks_total %>% filter(row_number() %in% train_inds)
hawks_test <- hawks_total %>% filter(row_number() %in% test_inds)

hawks_train_x <- hawks_train %>% select(!Species)
hawks_train_y <- hawks_train %>% pull(Species)

hawks_test_x <- hawks_test %>% select(!Species)
hawks_test_y <- hawks_test %>% pull(Species)
```

```{r}
hawks_train %>% nrow()
```

```{r}
hawks_test %>% nrow()
```

```{r}
predict_y <- function(y) {
  training_error_0 <- mean(abs(y-0))
  training_error_1 <- mean(abs(y-1))
  return (ifelse(training_error_1 > training_error_0, 0, 1))
}

predict_result <- predict_y(hawks_train_y)

print(predict_result)

cat("Train error =", sum(abs(hawks_train_y-predict_result)/length(hawks_train_y)), "\n")
cat("Test error =", sum(abs(hawks_test_y-predict_result)/length(hawks_test_y)))
```

```{r}
sum(hawks_train_y == 0) > sum(hawks_train_y == 1)
```

## 3

```{r}
lda_model <- MASS::lda(Species ~ ., data=hawks_train)
lda_train_predict <- predict(lda_model, hawks_train_x)$class %>% as.character() %>% as.numeric() 

lda_train_error <- sum(abs(hawks_train_y-lda_train_predict))/length(hawks_train_y)
cat("Train error = ", lda_train_error, "\n")

lda_test_predict <- predict(lda_model, hawks_test_x)$class %>% as.character() %>% as.numeric()
lda_test_error <- sum(abs(hawks_test_y-lda_test_predict))/length(hawks_test_y)
cat("Test error = ", lda_test_error)
```

## 4

```{r}
sigmoid <- function(z) {
  return (1/(1+exp(-z)))
}

x <- seq(-10, 10, 0.1)
y <- sigmoid(x)


ggplot(data=data.frame(x, y), aes(x=x, y=y)) + geom_line(color="blue") + labs(x="z", y="S(z)") + theme_bw()
```
```{r}
library(glmnet)
```

```{r}
logistic_model <- glmnet(x=hawks_train_x %>% as.matrix(), y=hawks_train_y, family = "binomial", alpha=0, lambda=0)

logistic_train_predicted_y <- predict(logistic_model, hawks_train_x%>%as.matrix(), type="class") %>% as.integer()

logistic_train_error <- mean(abs(hawks_train_y-logistic_train_predicted_y))
cat("Train error = ", logistic_train_error, "\n")

logistic_test_predicted_y <- predict(logistic_model, hawks_test_x%>%as.matrix(), type="class") %>% as.integer()

logistic_test_error <- mean(abs(hawks_test_y-logistic_test_predicted_y))
cat("Test error = ", logistic_test_error, "\n")
```

