---
title: "Assignment6"
output: html_notebook
---

## 1. A Gaussian model for Red tailed hawks

```{r}
library(Stat2Data)
library(tidyverse)
data("Hawks")
```

```{r}
RedTailedDf <- Hawks %>% filter(Species=="RT") %>% select(Weight, Tail, Wing)

RedTailedDf %>% head()
```
```{r}
# Answer
tail_RT <- RedTailedDf %>% pull(Tail)

mu_mle_RT <- mean(tail_RT, na.rm=TRUE)
var_mle_RT <- var(tail_RT, na.rm=TRUE)*((n-1)/n) # the denominator of var is n-1
sigma_mle_RT <- sqrt(var_mle_RT)

mu_mle_RT
var_mle_RT
sigma_mle_RT
```

```{r}
tail_inc<-seq(mu_mle_RT-3*sigma_mle_RT, mu_mle_RT+3*sigma_mle_RT,sigma_mle_RT*0.001) # generate indicies
colors<-c("MLE density"="red","Kernel density"="blue") # set color legend 

ggplot() + geom_line(data=data.frame(tail=tail_inc,Density=dnorm(tail_inc,mean=mu_mle_RT,sd=sigma_mle_RT)),aes(x=tail,y=Density,color="MLE density")) + geom_density(data=data.frame(tail_RT=tail_RT), aes(x=tail_RT,color="Kernel density"))+labs(y="Density function",color="Estimator") + theme_bw() + scale_color_manual(values=colors) + ylab("Tail length (mm)")

```

```{r}
dnorm(c(-10, -5, 0, 5, 10))
pnorm(c(-10, -5, 0, 5, 10))
```


## 2. Location estimators with Gaussian data

```{r}
set.seed(0)
num_trials_per_sample_size<-100
min_sample_size<-5
max_sample_size<-1000
sample_size_inc<-5
mu_0<-1
sigma_0<-3

simulation_df<-crossing(trial=seq(num_trials_per_sample_size),sample_size=seq(min_sample_size, max_sample_size,sample_size_inc)) %>% # create data frame of all pairs of sample_size and trial
  mutate(simulation=pmap(.l=list(trial,sample_size), .f=~rnorm(.y,mean=mu_0,sd=sigma_0))) %>% # simulate sequences of Gaussian random variables
  # compute the sample medians
  mutate(sample_md=map_dbl(.x=simulation,.f=median)) %>%
  # compute the sample mean
  mutate(sample_mn=map_dbl(.x=simulation, .f=mean)) %>%
  group_by(sample_size) %>% summarise(msq_error_md=mean((sample_md-mu_0)^2),msq_error_mn=mean((sample_mn-mu_0)^2))

simulation_df
```
```{r}
simulation_df%>%
  pivot_longer(cols=c(msq_error_md,msq_error_mn),
               names_to="Estimator",values_to="msq_error")%>%
  mutate(Estimator=case_when(Estimator=="msq_error_md"~"Median",
                             Estimator=="msq_error_mn"~"Mean"))%>%
  ggplot(aes(x=sample_size,y=msq_error,color=Estimator,linetype=Estimator))+
  geom_smooth()+theme_bw()+xlab("Sample size")+ylab("Mean square error")
```


```{r}
colors <- c("Mean"="red", "Median"="blue")
linetypes<-c("Mean"="solid", "Median"="dashed")

simulation_df %>% ggplot(aes(x=sample_size)) + labs(x="Sample size", y="Mean square error")  + geom_smooth(aes(y=msq_error_md, color="Median", linetype="Median")) + geom_smooth(aes(y=msq_error_mean, color="Mean", linetype="Mean")) + theme_bw() + scale_color_manual(name="Estimator", values=colors) + scale_linetype_manual(name="Estimator", values=linetypes) + xlim(0, 500) + ylim(0, 0.5)
```
## 3. Unbiased estimation of population variance

```{r}
set.seed(0)
mu <- 1
sigma <- 2
sample_size <- 1000

sample_data <- rnorm(sample_size, mu, sigma)
mu_mle <- mean(sample_data)

sigma_mle <- sum((sample_data - mu_mle)^2)/sample_size
sigma_u <- sum((sample_data - mu_mle)^2)/(sample_size-1)

mle_bias <- sigma_mle - sigma^2
u_bias <- sigma_u - sigma^2
```

```{r}
mle_bias
```

```{r}
u_bias
```

```{r}
# Answer

set.seed(0)
num_trials_per_sample_size<-1000
min_sample_size<-5
max_sample_size<-100
sample_size_inc<-5

mu_0<-1
sigma_0<-3

bias_simulation_df<-crossing(trial=seq(num_trials_per_sample_size), sample_size=seq(min_sample_size,max_sample_size, sample_size_inc))%>% # create data frame of all pairs of sample_size and trial
  mutate(simulation=pmap(.l=list(trial,sample_size), .f=~rnorm(.y,mean=mu_0,sd=sigma_0)))%>% # simulate sequences of Gaussian random variables
  mutate(var_u=map_dbl(.x=simulation,.f=var))%>% # compute the sample var with n-1 normalisation
  mutate(var_mle=pmap_dbl(.l=list(.x=simulation,.y=sample_size),.f=~(((.y-1)/.y)*var(.x))))%>% # compute the mle var estimate with n normalisation
  group_by(sample_size)%>%
  summarise(bias_var_u=mean(var_u)-sigma_0^2,bias_var_mle=mean(var_mle)-sigma_0^2)%>%
  pivot_longer(cols=c(bias_var_u,bias_var_mle), names_to="Estimator",values_to="Bias")%>%
  mutate(Estimator=case_when(Estimator=="bias_var_u"~"Unbiased",Estimator=="bias_var_mle"~"MLE"))

bias_simulation_df%>%
  ggplot(aes(x=sample_size,y=Bias,color=Estimator,linetype=Estimator))+
  geom_smooth()+
  theme_bw()+
  xlab("Sample size")+ylab("Bias")

bias_simulation_df
```
```{r}
set.seed(0)
num_trials_per_sample_size<-1000
min_sample_size<-5
max_sample_size<-100
sample_size_inc<-5
mu_0<-1
sigma_0<-3
bias_sd_simulation_df<-crossing(trial=seq(num_trials_per_sample_size),
                      sample_size=seq(min_sample_size,max_sample_size,
sample_size_inc))%>% # create data frame of all pairs of sample_size and trial
  mutate(simulation=pmap(.l=list(trial,sample_size),
                         .f=~rnorm(.y,mean=mu_0,sd=sigma_0)))%>%
  # simulate sequences of Gaussian random variables
mutate(sqrt_var_u=map_dbl(.x=simulation,.f=~sqrt(var(.x))))%>% # compute the sample sd
group_by(sample_size)%>%
    summarise(bias_sample_sd=mean(sqrt_var_u)-sigma_0)
bias_sd_simulation_df%>%
  ggplot(aes(x=sample_size,y=bias_sample_sd))+
  geom_smooth()+
theme_bw()+
xlab("Sample size")+ylab("Bias sample s.d.")
```
Remark: We expect a negative bias here since for a non-constant random variable Z we have $E(\sqrt{Z}) ≤ \sqrt{E(Z)}$.

---

## 5. Maximum likelihood estimation with the Poisson distribution  

```{r}
library(tidyverse)
```


```{r}
set.seed(0)
num_trails <- 1000
min_sample_size <- 5
max_sample_size <- 100
sample_size_inc <- 5
lambda_0 <- 0.5

# 20 Sample size, each have 1000 trails.
poisson_simulation_df <- crossing(trials=seq(num_trails), sample_size=seq(min_sample_size, max_sample_size, sample_size_inc))


# The map functions transform their input by applying a function to each element of a list or atomic vector and returning an object of the same length as the input.
help(map)

help(map2)

# So, here we can not use normal map function, like map_dbl.
# Contrary, we use multiple inputs map like map2 and pmap
poisson_simulation_df <- poisson_simulation_df %>% mutate(simulation=pmap(.l=list(trials, sample_size), .f=~rpois(.y, lambda_0)))

poisson_simulation_df <- poisson_simulation_df %>% mutate(simulation=map2(.x=trials, .y=sample_size, .f=~rpois(.y, lambda_0)))

help(pmap) # Map over multiple inputs simultaneously.

# compute the sample mean
poisson_simulation_df <- poisson_simulation_df %>% mutate(lambda_mle=map_dbl(simulation, .f=mean))

# compute the mean square error
poisson_simulation_df <- poisson_simulation_df %>% group_by(sample_size) %>% summarise(msq_error=mean((lambda_mle-lambda_0)^2))

poisson_simulation_df %>% ggplot(aes(x=sample_size, y=msq_error)) + geom_smooth() + theme_bw() 
```

```{r}
folder_name <- "resources"
file_name <- "VonBortkiewicz"

bortkiewicz_horsekick_data<-read.csv(paste0(folder_name,"/",file_name,".csv"))

bortkiewicz_horsekick_data
```
```{r}
horse_kick_fatalities<-bortkiewicz_horsekick_data%>%pull(fatalities)
lambda_MLE=mean(horse_kick_fatalities)
lambda_MLE

dpois(0, lambda=lambda_MLE)
```

```{r}
set.seed(0)
trails <- 1000
min_sample_size <- 5
max_sample_size <- 100
sample_size_inc <- 5
lambda_0 = 0.5

poisson_simulation <- crossing(trails=seq(trails), sample_size=seq(min_sample_size, max_sample_size, sample_size_inc)) %>% mutate(simulation=pmap(.l=list(trails, sample_size), .f=~rpois(.y, lambda_0))) %>% mutate(lambda_mle=map_dbl(simulation, .f=mean))

poisson_simulation <- poisson_simulation %>% group_by(sample_size) %>% summarise(value=sqrt(trails/lambda_0) * (mean(lambda_mle)-lambda_0))

poisson_simulation
```

```{r}
set.seed(0)
num_trails <- 1000
min_sample_size <- 5
max_sample_size <- 100
sample_size_inc <- 5
lambda_0 = 0.5

# 20 Sample size, each have 1000 trails.
poisson_simulation_df <- crossing(trials=seq(num_trails), sample_size=seq(min_sample_size, max_sample_size, sample_size_inc))  %>% mutate(simulation=pmap(.l=list(trials, sample_size), .f=~rpois(.y, lambda_0)))

# compute the sample mean
poisson_simulation_df <- poisson_simulation_df %>% mutate(lambda_mle=map_dbl(simulation, .f=mean))

# compute the mean square error
poisson_simulation_df <- poisson_simulation_df %>% group_by(sample_size) %>% summarise(estimate=sqrt(num_trails/lambda_0) * (mean(lambda_mle)-lambda_0))


poisson_simulation_df %>% ggplot(aes(x=sample_size, y=estimate)) + geom_smooth() + theme_bw() 
```

## 6. Maximum likelihood estimation for the exponential distribution  

```{r}
folder_name <- "resources"
file_name <- "CustomerPurchases"

customer_data <- read.csv(paste0(folder_name,"/",file_name,".csv"))
customer_data
```

```{r}
help(lead)

customer_data <- customer_data %>% mutate(time_diffs=lead(Time)-Time)
customer_data

time_diffs_sequence <- customer_data %>% pull(time_diffs)
lambda_mle <- 1/mean(time_diffs_sequence, na.rm=TRUE)
```

```{r}
1-pexp(60, lambda_mle)
```

