---
title: "Assignment 8"
output: html_notebook
---

```{r}
library(tidyverse)
library(palmerpenguins)

peng_AC <- penguins %>% drop_na(species, body_mass_g) %>% filter(species!="Gentoo")
```

```{r}
t_test_function <- function(data, val_col, group_col) {
  data <- data %>% select(c(val_col, group_col)) # Select necessary columns for processing.
  data <- data %>% group_by(.data[[group_col]]) %>% summarise(sample_mean=mean(.data[[val_col]]), sample_sd=sd(.data[[val_col]]), sample_size=n()) # Generating sample mean, sample variance and sample size of each group.
  sample_x0 <- data[1,] # Sample x0
  sample_x1 <- data[2,] # Sample x1
  mu_0 <- sample_x0["sample_mean"][[1]]
  mu_1 <- sample_x1["sample_mean"][[1]]
  sd_0 <- sample_x0["sample_sd"][[1]]
  sd_1 <- sample_x1["sample_sd"][[1]]
  size_0 <- sample_x0["sample_size"][[1]]
  size_1 <- sample_x1["sample_size"][[1]]
  sd_combind <- sqrt(((size_0-1)*sd_0^2+(size_1-1)*sd_1^2)/(size_0+size_1-2))
  t_statistic <- (mu_0-mu_1)/(sd_combind*sqrt(1/size_0+1/size_1))
  p_values <- 2*(1-pt(abs(t_statistic), df=size_0+size_1-2))
  effect_size <- (mu_0-mu_1)/sd_combind
  return (data.frame(t_stat=t_statistic, dof=effect_size, p_val=p_values))
}
```

```{r}
help(t.test)
```


```{r}
group_col <- "species"
peng_AC %>% group_by(!!(group_col))
```


```{r}
t.test(body_mass_g~species, data=peng_AC,var.equal = TRUE)
```

```{r}
t_test_function(peng_AC,"body_mass_g","species")
```

## 4. Investigating test size for an unpaired Student's t-test

```{r}
num_trials<-10000
sample_size<-30
mu_0<-1
mu_1<-1
sigma_0<-3
sigma_1<-3
alpha<-0.05

set.seed(0) # set random seed for reproducibility

single_alpha_test_size_simulation_df<-data.frame(trial=seq(num_trials))%>%
  mutate(sample_0=map(.x=trial,.f=~rnorm(n=sample_size,mean=mu_0,sd=sigma_0)),
         sample_1=map(.x=trial,.f=~rnorm(n=sample_size,mean=mu_1,sd=sigma_1)))%>%
  # generate random Gaussian samples 
  mutate(p_value=pmap(.l=list(trial,sample_0,sample_1),
                      .f=~t.test(..2,..3,var.equal = TRUE)$p.value))%>%
  # generate p values
  mutate(type_1_error=p_value<alpha)

single_alpha_test_size_simulation_df %>%
  pull(type_1_error) %>%
  mean()
```

